plugins:
  atproto_auth_enabled:
    default: false
    validator: "EnableAtprotoValidator"
    area: "authenticators"
  atproto_auth_private_key:
    default: ""
    textarea: true
    area: "authenticators"
  atproto_auth_authorization_server:
    default: "https://bsky.social"
    area: "authenticators"
